contentdir = "content"
layoutdir = "layouts"
publishdir = "public"
theme = "macromealey2017"
baseurl = "http://macromealey.tech"
languageCode = "en-us"
title = "MacroMealey"
[taxonomies]
tag = "tags"
